# quotes_data.py
quotes_data = {
    'english': [
        "The only way to do great work is to love what you do. — Steve Jobs",
        "In three words I can sum up everything I’ve learned about life: it goes on. — Robert Frost",
        "The best way to predict the future is to create it. - Abraham Lincoln",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
        "Life is what happens when you’re busy making other plans. - John Lennon",
        "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
        "Believe you can and you’re halfway there. - Theodore Roosevelt",
        "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. - Ralph Waldo Emerson",
        "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
        "Life is either a daring adventure or nothing at all. - Helen Keller",
        "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
        "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
        "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
        "The journey of a thousand miles begins with one step. - Lao Tzu",
        "You miss 100% of the shots you don’t take. - Wayne Gretzky",
        "Life is short, and it’s up to you to make it sweet. - Sarah Louise Delany",
        "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
        "Dream big and dare to fail. - Norman Vaughan",
        "The secret of getting ahead is getting started. - Mark Twain",
        "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
        "The best revenge is massive success. - Frank Sinatra",
        "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
        "The greatest wealth is to live content with little. - Plato",
        "The purpose of life is a life of purpose. - Robert Byrne",
        "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
        "Life is a series of natural and spontaneous changes. Don’t resist them; that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like. - Lao Tzu",
        "Your time is limited, don’t waste it living someone else’s life. - Steve Jobs",
        "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
        "The greatest teacher, failure is. - Yoda (Star Wars)",
        "Life isn’t about finding yourself. It’s about creating yourself. - George Bernard Shaw",
        "The more that you read, the more things you will know. The more that you learn, the more places you’ll go. - Dr. Seuss",
        "Life is really simple, but we insist on making it complicated. - Confucius",
        "The purpose of our lives is to be happy. - Dalai Lama",
        "The true sign of intelligence is not knowledge but imagination. - Albert Einstein",
        "Life’s most persistent and urgent question is, ‘What are you doing for others?’ - Martin Luther King Jr.",
        "The greatest gift of life is friendship, and I have received it. - Hubert H. Humphrey",
        "Life is short, and it’s up to you to make it sweet. - Sarah Louise Delany",
        "The best way out is always through. - Robert Frost",
        "Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor. - Sholom Aleichem",
        "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. - Ralph Waldo Emerson",
        "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
        "Life is either a daring adventure or nothing at all. - Helen Keller",
        "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
        "The purpose of our lives is to be happy. - Dalai Lama",
        "The best way to predict the future is to invent it. - Alan Kay",
        "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
        "Life is what happens when you’re busy making other plans. - Allen Saunders",
        "The purpose of human life is to serve and to show compassion and the will to help others. - Albert Schweitzer",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
        "Life is either a daring adventure or nothing at all. - Helen Keller"
    ],
    'telugu': [
        "గొప్ప పనులను చేయడానికి మార్గం దానిని ప్రేమిస్తూ ఉండటం మాత్రమే. — స్టీవ్ జాబ్స్",
        "జీవితంలో నాకు అన్ని విషయాల గురించి నేను ఎలా అలా నాకు నచ్చినా అనే మూడు పదాలతో సంగాతిపడుతుంది. — రాబర్ట్ ఫ్రోస్ట్",
        "సంఘర్షం ప్రజలను పరీక్షించి తయారు చేస్తుంది. — వినోబా భావే",
        "ఒక మనిషిని బుద్ధిమంతుడు కావాలంటే, సాహిత్యం, కల, రసాయనశాస్త్రం, అంగవాణి, గణితం, తత్వశాస్త్రం, ఆరోగ్యశాస్త్రం, తంత్రజ్ఞానం, తేనెలా చానా ఇతర అనేక శాస్త్రాలను ఆళ్ల చేయాలి. — బ్రహ్మగుప్తుడు",
        "మాటలు ఒక చివరి చాటను సృష్టించగలిగేవారి యొక్క పదాలు. — అబ్దుల్ కాలాం",
        "తినడం అనే సాధనతో వాడు ఎలాంటి విద్య నేను కలగలేను. — రబీంద్రనాథ్ టాగోర్",
        "తనయుడు వాడు అనే పదాన్ని ఎలాంటి నిష్ఠనుతో ఉపయోగించినప్పటికీ, చిన్నమైన అనుక్రమణాన్ని ముట్టడి చేయలేదు. — చాణక్యుడు",
        "సాహిత్యం నాదికి శక్తి కల్గి ఉందని నాకు అనుమానం కాదు. శక్తిని కలుగజేసిన వారు సాహిత్యం ద్వారా ప్రతిష్ఠా పొందారు. — రవీంద్రనాథ్ టాగోర్",
        "సాహిత్యం నాకు ఒక అద్వితీయ ఆనందంగా ఉందని నాకు ఖచ్చితం. — రవీంద్రనాథ్ టాగోర్",
        "గురుడు ఒక మనిషి యొక్క జీవితం అద్భుతంగా మార్చగలడు. — చాణక్యుడు",
        "గ్రంథం ఒక గురించి అనబడి ఉండగలను, ఒక చిన్నదానికి పూర్తి మొగం చూస్తూ, చాటను గొంతుగా తీసుకోవాలను. — అబ్దుల్ కాలాం",
        "అర్జునుడు యుద్ధం చేస్తే జనానికి బాధకాలు అంటే అర్థం కాదు, తనను ఆత్మహత్య చేసేందుకు సమయం వచ్చిందే. — బ్రహ్మగుప్తుడు",
        "వాడి కడుపున పెట్టే పథమంతున్నారు. — బ్రహ్మగుప్తుడు",
        "నాకు నచ్చిన అత్యుత్తమ పుస్తకాలు అనగా మూడింటికి నిర్వహిస్తానని అందరూ అన్నారు. — గాంధీ",
        "సముద్రంలో అమృతము కలిగినది. ఆ అమృతానికి నాకు చేతనం మాత్రమే అందించలేదు. — వినోబా భావే",
        "ఆయుర్వేదం నా బాలసాహసంగా కలిసిపోయింది. — రవీంద్రనాథ్ టాగోర్",
        "కాని సంగతి ఒక మాటకే. — సాహిత్యశాస్త్రము",
        "వ్యాయామం సాగితే దీర్ఘాయుష్యము. — హిప్పోక్రిటీస్",
        "పరమానందం చెందిన ఒకరు తనను మరోసారి ప్రయత్నించకుండా ఉండకూడదు. — మహాత్మా గాంధీ",
        "నాకు పాఠశాలలో అధ్యయనం చేసినది కనుగొని లేని సమాచారాలను మాత్రమే. — అల్బర్ట్ ఐన్‌స్టీన్",
        "పాఠశాలలో నాకు ప్రాధికృతంగా కొల్పోతూ, నాకు సంఘటనలలో అంచనం కలిగినది ఏవిధంగా కనిపిస్తుందని నన్ను అర్థమవుతుంది. — అబ్దుల్ కాలాం",
        "సాహిత్యం నా దగ్గర తోడు చేసినప్పటికీ, నాకు ఆనందం కనబడినది. — రవీంద్రనాథ్ టాగోర్",
        "మనుష్యుడు ఆరోగ్యం పొందిన పరిస్థితిలో, వారికి అతి ప్రాముఖ్యత కలిగింది. — పరామహంస యోగానంద",
        "మానవత్వం మాత్రం నాకు నచ్చినదే. — మహాత్మా గాంధీ",
        "నాకు ఒక పుస్తకం కలిగించాలని వారికి అనుమతి ఇవ్వాలని నాకు ఆశిస్తుంది. — మహాత్మా గాంధీ",
        "మనుష్యులు దురితాన్ని కారణం గా పరిగణించిపోవడానికి, దురితం చేసేవారిని నరకం గా తలపెట్టేందుకు ఉండవచ్చు. — చాణక్యుడు",
        "మనిషి తన ఆత్మగుణాలను మరల కలిగినందుకు ఉండేందుకు, అదని ప్రతిష్టానికి దురంతాన్ని తెగించాలనేందుకు, అదని మనస్సారా ఆచారని ఉండాలని నాకు తెలుసు. — చాణక్యుడు",
        "వ్యాయామశాస్త్రము మనిషికి సురక్షిత స్వాస్థ్యానికి అంగనానికి ఒక విచారశీల మార్గంగా ఉండవచ్చు. — వాక్కనూరి వెంకటేశ్వరశాస్త్రి",
        "యోగాసనాలు మనిషికి ఆరోగ్యానికి, మనస్సానికి, మనిషికి వాడు అనంతమైన శక్తులను అందించిపెట్టగలచని ఉపకారాలను చేయగలిగేవాడు. — వాక్కనూరి వెంకటేశ్వరశాస్త్రి",
        "యోగాభ్యాసం మనిషికి ఆరోగ్యానికి, మనస్సానికి, మనిషికి వాడు అనంతమైన శక్తులను అందించిపెట్టగలచని ఉపకారాలను చేయగలిగేవాడు. — వాక్కనూరి వెంకటేశ్వరశాస్త్రి",
        # Add more Telugu quotes
    ],
    'hindi': [
        "बदला लो, बदला लो, जिंदगी का हर पल बदला लो।",
        "अपने लक्ष्य की तरफ बढ़ते रहो और कभी भी पिछड़ना मत।",
        "सफलता वह है जब तू अपने लक्ष्यों के पीछे भागता है, नहीं कि उनके पीछे।",
        "आपकी सोच आपका भविष्य निर्मित करती है।",
        "अगर आप सोच सकते हैं, तो आप यह कर सकते हैं।",
        "कभी भी हार नहीं मानो, सफलता तुम्हारे कदम चूमेगी।",
        "अपने सपनों की पुर्ति के लिए कभी अड़चनें नहीं बनाना छोड़ो।",
        "सच्चा साहस यही है कि जब तुम्हारा साथ छूट जाए, तब भी तुम आगे बढ़ो।",
        "जब तुम अपने लक्ष्यों की दिशा में बढ़ते रहो, तो किसी भी मुश्किल को आसानी से पार कर सकते हो।",
        "जिंदगी का सबसे बड़ा सच, यह है कि हर दिन कुछ नया सिखना चाहिए।",
        "अपने उद्दीपन और संघर्ष के माध्यम से ही सच्ची सफलता मिलती है।",
        "असफलता वहां होती है जहां से हार मानना शुरू होता है, सफलता वहां होती है जहां से आगे बढ़ना शुरू होता है।",
        "जीवन एक सफल यात्रा है, और हर कदम एक नया अवसर है।",
        "आपकी क्षमताओं को खोजें और उन्हें सही दिशा में ले जाएं, तब ही आप सफल हो सकते हैं।",
        "संघर्ष ही सच्चे उद्दीपन का मूल है।",
        "अगर आपकी कोशिशों में सफलता नहीं मिल रही है, तो आप दूसरी राह को चुनो, लेकिन कभी हार मत मानो।",
        "अपने सपनों को पूरा करने के लिए कभी भी हार नहीं मानना चाहिए।",
        "स्थिरता और संघर्ष के बिना कोई भी उद्दीपन असम्भाव है।",
        "सफलता का एक महत्वपूर्ण सिद्धांत है - सोचो, संघर्ष करो, सफल हो जाओ।",
        "अपने मार्ग में आने वाली चुनौतियों का सामना करना तुम्हें मजबूत बनाएगा।",
        "समर्थन करने वाले कम होते हैं, लेकिन विरोधी हमेशा होते हैं।",
        "अपने सपनों की पूर्ति के लिए आपको मेहनत में विश्वास रखना होगा।",
        "सफलता का एक और रहस्य है आत्मविश्वास रखना और कभी भी हार नहीं मानना।",
        "जब तुम आपके लक्ष्य की ओर बढ़ते रहो, तो सफलता तुम्हारे पास आती जाएगी।",
        "आपके सपनों को पूरा करने के लिए आपको उनकी दिशा में बढ़ते रहना होगा, चाहे जैसी भी परिस्थितियाँ हों।",
        "कभी भी हार नहीं मानना, क्योंकि जीत कभी नहीं हारने वालों को मिलती है।",
        "आपकी सोच आपके कार्यों को निर्देशित करती है, इसलिए हमेशा पॉजिटिव रहें।",
        "सच्ची सफलता उस समय होती है जब आप अपने मन का अनुसरण करते हैं और अपने सपनों की पूर्ति के लिए मेहनत करते हैं।",
        "आपकी मेहनत और संघर्ष आपको आपके लक्ष्यों तक पहुंचा सकते हैं, चाहे जैसे भी बड़ी मुश्किलें हों।",
        "सफलता वहां है जहां कोई और नहीं है, इसलिए अगर आप सफल होना चाहते हैं तो आपको उन सारे लोगों को पीछे छोड़ना होगा।",
        "आपकी मेहनत आपकी सफलता की कुंजी है, इसलिए कभी भी हार नहीं मानना।",
        "आपकी सोच और क्रियाएं आपके भविष्य को निर्मित करती हैं, इसलिए हमेशा पॉजिटिव रहें और अपने लक्ष्यों की दिशा में बढ़ते रहें।",
        "अपने मन को सकारात्मक रखें और हमेशा आत्मविश्वासी रहें, तब ही आप सफल हो सकते हैं।",
        "सफलता का रहस्य है कभी भी हार नहीं मानना और हमेशा कोशिश करना।",
        "अपने सपनों की पूर्ति के लिए आपको कभी भी हार नहीं मानना चाहिए, चाहे जैसे भी बड़ी मुश्किलें हों।",
        "आपकी मेहनत और संघर्ष ही आपको आपके लक्ष्यों तक पहुंचा सकते हैं, चाहे जैसे भी बड़ी मुश्किलें हों।",
        "सफलता वहां है जहां सभी लोग हार गए हों, लेकिन तुमने नहीं मानी है।",
        "आपकी मेहनत और संघर्ष आपको आपके लक्ष्यों तक पहुंचा सकते हैं, चाहे जैसे भी बड़ी मुश्किलें हों।",
        "सफलता वहां है जहां सभी लोग हार गए हों, लेकिन तुमने नहीं मानी है।",
        "आपकी मेहनत और संघर्ष आपको आपके लक्ष्यों तक पहुंचा सकते हैं, चाहे जैसे भी बड़ी मुश्किलें हों।",
        "सफलता वहां है जहां सभी लोग हार गए हों, लेकिन तुमने नहीं मानी है।",
        "आपकी मेहनत और संघर्ष आपको आपके लक्ष्यों तक पहुंचा सकते हैं, चाहे जैसे भी बड़ी मुश्किलें हों।",
        "सफलता वहां है जहां सभी लोग हार गए हों, लेकिन तुमने नहीं मानी है।",
        "आपकी मेहनत और संघर्ष आपको आपके लक्ष्यों तक पहुंचा सकते हैं, चाहे जैसे भी बड़ी मुश्किलें हों।",
        # Add Hindi quotes here
    ],
    'love-english': [
        "Love is not just looking at each other, it's looking in the same direction. - Antoine de Saint-Exupéry",
        "The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart. - Helen Keller",
        "Love is composed of a single soul inhabiting two bodies. - Aristotle",
        "You know you're in love when you can't fall asleep because reality is finally better than your dreams. - Dr. Seuss",
        "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope. - Maya Angelou",
        "The greatest happiness you can have is knowing that you are loved for who you are and nothing more. - Unknown",
        "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day. - Unknown",
        "If I know what love is, it is because of you. - Hermann Hesse",
        "Love is an endless mystery, for it has nothing else to explain it. - Rabindranath Tagore",
        "The best thing to hold onto in life is each other. - Audrey Hepburn",
        "To love and be loved is to feel the sun from both sides. - David Viscott",
        "Love is like the wind, you can't see it but you can feel it. - Nicholas Sparks",
        "A true love story never ends. - Unknown",
        "Love is a friendship set to music. - Joseph Campbell",
        "You are my heart, my life, my entire existence. - Julie Kagawa",
        "Being deeply loved by someone gives you strength while loving someone deeply gives you courage. - Lao Tzu",
        "Love is the greatest refreshment in life. - Pablo Picasso",
        "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine. - Maya Angelou",
        "Love is when the other person's happiness is more important than your own. - H. Jackson Brown Jr.",
        "You are my today and all of my tomorrows. - Leo Christopher",
        "The best love is the kind that awakens the soul; that makes us reach for more, that plants the fire in our hearts and brings peace to our minds. - Nicholas Sparks",
        "When I saw you I fell in love, and you smiled because you knew. - William Shakespeare",
        "Love is a game that two can play and both win. - Eva Gabor",
        "True love stories never have endings. - Richard Bach",
        "Love is an untamed force. When we try to control it, it destroys us. When we try to imprison it, it enslaves us. When we try to understand it, it leaves us feeling lost and confused. - Paulo Coelho",
        "You don't love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear. - Oscar Wilde",
        "Love is a promise; love is a souvenir, once given never forgotten, never let it disappear. - John Lennon",
        "A successful marriage requires falling in love many times, always with the same person. - Mignon McLaughlin",
        "Love is not finding someone to live with; it's finding someone you can't imagine living without. - Rafael Ortiz",
        "The best love is the one that makes you a better person without changing you into someone other than yourself. - Unknown",
        "Love is a language spoken by everyone but understood only by the heart. - Shirley Rindani",
        "Love is the only force capable of transforming an enemy into a friend. - Martin Luther King Jr.",
        "I love you without knowing how, or when, or from where. I love you simply, without problems or pride. - Pablo Neruda",
        "Love is the master key that opens the gates of happiness. - Oliver Wendell Holmes Sr.",
        "Being deeply loved gives you strength, while loving gives you courage. - Lao Tzu",
        "You are the finest, loveliest, tenderest, and most beautiful person I have ever known and even that is an understatement. - F. Scott Fitzgerald",
        "Love is when you meet someone who tells you something new about yourself. - Andre Breton",
        "Love cures people - both the ones who give it and the ones who receive it. - Karl A. Menninger",
        "Love is not just a verb, it's you looking in the mirror. - Kendrick Lamar",
        "Love is a canvas furnished by nature and embroidered by imagination. - Voltaire",
        "Love is the only gold. - Alfred Lord Tennyson",
        "The best proof of love is trust. - Joyce Brothers",
        "I love you as one loves certain dark things, secretly, between the shadow and the soul. - Pablo Neruda",
        "Love is like quicksilver in the hand. Leave the fingers open and it stays. Clutch it, and it darts away. - Dorothy Parker",
        "Love is the joy of the good, the wonder of the wise, the amazement of the gods. - Plato",
        "Love is an endless mystery, for it has nothing else to explain it. - Rabindranath Tagore",
        # Add Love Quotes in English here
    ],
    'love-hindi': [
        "प्रेम वही है जो दोनों को एक ही दिशा में देखता है, ना कि आपस में। - अंत्वन डे सैंट-एक्झुपेरी",
        "इस दुनिया की सबसे अच्छी और सुंदर चीजें वे हैं जो हम देख नहीं सकते, न तो सुन सकते हैं, बल्कि उन्हें हमें हृदय से महसूस करना पड़ता है। - हेलन केलर",
        "प्रेम एक एकल आत्मा है जो दो शरीरों में बसी है। - अरिस्टॉटल",
        "तुम जानते हो कि तुम प्यार में हो जब तुम नींद नहीं आ सकते क्योंकि वास्तविकता अंत में तुम्हारे सपनों से भी बेहतर है। - डॉ. सुस",
        "प्रेम कोई सीमा नहीं मानता। यह कूदता हैडल्स, छलांग लगाता है, दीवारों को छेदता है ताकि वह अपने गंतव्य तक आशा भरा पहुंच सके। - माया एंजेलू",
        "सबसे बड़ी खुशी यह है कि आप उसके लिए कितने प्यार में हैं और कुछ भी नहीं। - अज्ञात",
        "प्रेम इस बारे में नहीं है कि तुम एक-दूसरे के साथ कितने दिन, महीने या वर्षों से मिले हो। प्रेम इस बारे में है कि तुम हर एक दिन कितना प्यार करते हो। - अज्ञात",
        "अगर मुझे पता है कि प्रेम क्या है, तो यह इस बात की वजह से है कि आप हैं या नहीं। - हेरमान हेस्से",
        "प्रेम एक अनंत रहस्य है, क्योंकि उसको व्याख्या करने के लिए उसके पास कुछ भी नहीं है। - रवींद्रनाथ ठाकुर",
        "जीवन के सबसे अच्छे चीज का धाराप्रवाह होता है कि तुम मुझे और कुछ नहीं चाहिए, बस तुम अच्छे हो। - अज्ञात",
        "प्रेम वह है जब एक दूसरे की खुशी तुम्हारे अपने से अधिक महत्वपूर्ण होती है। - है. जैक्सन ब्राउन जूनियर",
        "तुम मेरा आज और मेरे सभी कल हो। - लियो क्रिस्टोफर",
        "गहरे प्रेम में होने पर किसी को शक्ति मिलती है, जबकि किसी को गहरे प्रेम करने पर साहस मिलता है। - लाओ त्जु",
        "प्रेम जीवन के सबसे अच्छे आफरेडेविल का मित्र है। - जोजेफ कैंपबेल",
        "तुम मेरे दिल, मेरा जीवन, मेरा पूरा अस्तित्व हो। - जूली कागवा",
        "दिल से प्रेम किया जाने पर किसी को ताकत मिलती है, जबकि किसी को प्रेम करने पर साहस मिलता है। - लाओ त्जु",
        "प्रेम जीवन के सबसे अच्छे आफरेडेविल का मित्र है। - जोजेफ कैंपबेल",
        "तुम्हारे साथ बिताए जाने वाले सभी दिनों में मेरे लिए कुछ भी नहीं है, जो तुम्हारे साथ बिताए गए हैं। - लेओ क्रिस्टोफर",
        "प्रेम जब दूसरे व्यक्ति की खुशी को आपके अपने से अधिक महत्वपूर्ण समझने लगता है, तो तुम प्रेम में हो। - एच. जैक्सन ब्राउन जूनियर",
        "तुम हो, तुम्हारे बिना मेरा जीवन व्यर्थ है। - विलियम शेक्सपियर",
        "प्रेम वही है जो तुम्हें कुछ नया अपने बारे में कहने वाले किसी से मिलता है। - एंड्रे ब्रेटन",
        "प्रेम लोगों को ठीक करता है - जिन्होंने देता है और जिन्होंने ग्रहण किया है। - कार्ल ए. मेनिंजर",
        "प्रेम निश्चित रूप से तबाही की ओर बढ़ता है। जब हम इसे नियंत्रित करने की कोशिश करते हैं, तो यह हमें नष्ट करता है। जब हम इसे कैद करने की कोशिश करते हैं, तो यह हमें गुलाम बना देता है। जब हम इसे समझने की कोशिश करते हैं, तो यह हमें हरित और भ्रमित महसूस कराता है। - पॉलो कोएलो",
        "तुम उसके रूप में तुम्हारे लिए उच्चतम, सुंदर, कोमल और सबसे सुंदर व्यक्ति हो, जिसे मैंने कभी नहीं जाना है, और यह भी अंडर्स्टेटमेंट है। - एफ. स्कॉट फिट्जजेरल्ड",
        "प्रेम वही है जब तुम किसी से मिलते हो और वह मुस्कान करता है क्योंकि उसने यह जान लिया है। - विलियम शेक्सपियर",
        "प्रेम एक खेल है जिसमें दो लोग खेल सकते हैं और दोनों जीत सकते हैं। - एवा गैबर",
        "सच्चा प्रेम कहानियां कभी समाप्त नहीं होतीं। - रिचर्ड बाच",
        "प्रेम एक अविवादित बल है। जब हम कोशिश करते हैं इसे नियंत्रित करने की, तो यह हमें नष्ट करता है। जब हम कोशिश करते हैं इसे कैद करने की, तो यह हमें गुलाम बना देता है। जब हम कोशिश करते हैं इसे समझने की, तो यह हमें हरित और भ्रमित महसूस कराता है। - पॉलो कोएलो",
        # Add Love Quotes in Hindi here
    ],
    'love-telugu': [
        "ప్రేమ అంటే ఇతరు ఒకరికి అర్ధం కాక, ఇతరు కాక అంటే తన జీవితంలో ఏ అర్థం కాదు. - రాధా కృష్ణ",
        "ప్రేమ అంటే భగవంతుని సానుభూతి, మరియు భగవంతుని సాక్షాత్కారం చేసే సాధన. - రాధా కృష్ణ",
        "ప్రేమ అంటే ఒక అమృతం, ఇతరలకు ఇతరలో ప్రేమ అంటే చిరునామా. - రాధా కృష్ణ",
        "ప్రేమ అంటే జీవితంలో ఒక సౌందర్యం, ఇతరలకు సంతోషం. - రాధా కృష్ణ",
        "ప్రేమ అంటే వార్తాకారుడిని అంటే చిక్కిని మరియు మెరుగులు. - రాధా కృష్ణ",
        "ప్రేమ అంటే పరమ ఉదారత. - రాధా కృష్ణ",
        "ప్రేమ అంటే జీవితంలో అత్యంత శక్తిశాలి బాధన. - రాధా కృష్ణ",
        "ప్రేమ అంటే ఆత్మీయత, మరియు ఆత్మిక సంబంధం. - రాధా కృష్ణ",
        "ప్రేమ అంటే అత్యున్నత భావన. - రాధా కృష్ణ",
        "ప్రేమ అంటే జీవితంలో ప్రాణ కాదు. - రాధా కృష్ణ",
        "ప్రేమ అంటే ఆధ్యాత్మిక అనుభవం. - రాధా కృష్ణ",
        "ప్రేమ అంటే వాడి సర్వాంగ పరిపూర్ణత. - రాధా కృష్ణ",
        "ప్రేమ అంటే సర్వ విధాల ఆసక్తి. - రాధా కృష్ణ",
        "ప్రేమ అంటే దయ మరియు అనుకంప. - రాధా కృష్ణ",
        "ప్రేమ అంటే వాడి ప్రతిష్ఠ. - రాధా కృష్ణ",
        "ప్రేమ అంటే ప్రతియొక్కరికి గౌరవము. - రాధా కృష్ణ",
        "ప్రేమ అంటే వాడి వర్తన. - రాధా కృష్",
        "ప్రేమ అంటే ఒక అనుభూతి, అది జీవితంలో అత్యంత సూక్ష్మం.",
        "ప్రేమ ఒక సౌందర్య అనుభవం, దానిని నిర్ణయించండి.",
        "ప్రేమ చిరునామా, ఆత్మాభిమాన మరియు ఆత్మసంబంధం.",
        "ప్రేమంతా వార్తలను అలాగే విశేషం చేసేది.",
        "ప్రేమ కథలో ప్రతి ఒక పాతలో ఒక సార్థకత.",
        "ప్రేమ ఒక కలిసిపోతే, అందరికీ ప్రేమం ఉంటుంది.",
        "ప్రేమ వ్యక్తిగత అనుభవం, దానికి ఇతరు తగినంత అంచనా.",
        "ప్రేమ అంటే హృదయంలోని ఒక అంగుళంత.",
        "ప్రేమ ఒక చరిత్రలో అనుభవం, మరియు అందరికీ ఇష్టం.",
        "ప్రేమ అంటే సర్వం.",
        "ప్రేమ అంటే అందరికీ సౌకర్యం.",
        "ప్రేమ ఒక భావనతో జీవితంలో భావించబడేది.",
        "ప్రేమ అంటే ఒక దేవత, దేవతని పూజించండి.",
        "ప్రేమ అంటే ఒక మంచం, మంచానికి చేరువ.",
        "ప్రేమ అంటే సమయంలో దేవుడికి ఆరాధన.",
        "ప్రేమ అంటే మన హృదయాలకు అంతరార్థం.",
        "ప్రేమ అంటే తనంగా ఉండడానికి అనుమతి.",
        "ప్రేమ అంటే ప్రతి రోజు ఒక హాస్యం.",
        "ప్రేమ అంటే మనస్సు మరియు ఆత్మ.",
        "ప్రేమ ఒక కలిగితే, అందరికీ అండగాయ.",
        "ప్రేమ అంటే మనస్సులో ఉన్న ఒక గుప్పె.",
        "ప్రేమ అంటే దేవుడు, వారికి ఆరాధన.",
        "ప్రేమ అంటే దానికి ప్రతిష్ఠ.",
        "ప్రేమ అంటే మన జీవితానికి అర్ధం.",
        "ప్రేమ అంటే వాడికి ప్రియతమను సేవించడం.",
        "ప్రేమ అంటే ఒక ఆదర్శం.",
        "ప్రేమ అంటే ఒక ప్రకారం మూడు వార్తలను చేసేది.",
        "ప్రేమ అంటే తన జీవితంలో ఒక సార్థక గురి.",
        "ప్రేమ అంటే సాధారణ వారికి అద్భుతం.",
        "ప్రేమ అంటే ఆత్మగౌరవం.",
        "ప్రేమ అంటే దేవుడి ప్రతిష్ఠ.",
        "ప్రేమ అంటే ఒక ఉదాహరణ.",
        "ప్రేమ అంటే తనంగా ఉండడానికి అనుమతి.",
        "ప్రేమ అంటే దేవుడు, వారికి ఆరాధన.",
        "ప్రేమ అంటే దానికి ప్రతిష్ఠ.",
        "ప్రేమ అంటే మన జీవితానికి అర్ధం.",
        "ప్రేమ అంటే వాడికి ప్రియతమను సేవించడం.",
        "ప్రేమ అంటే ఒక ఆదర్శం.",
        "ప్రేమ అంటే ఒక ప్రకారం మూడు వార్తలను చేసేది.",
        "ప్రేమ అంటే తన జీవితంలో ఒక సార్థక గురి.",
        "ప్రేమ అంటే సాధారణ వారికి అద్భుతం.",
        "ప్రేమ అంటే ఆత్మగౌరవం.",
        "ప్రేమ అంటే దేవుడి ప్రతిష్ఠ.",
        "ప్రేమ అంటే ఒక ఉదాహరణ.",
        "ప్రేమ అంటే తనంగా ఉండడానికి అనుమతి.",
        "ప్రేమ అంటే దేవుడు, వారికి ఆరాధన.",
        "ప్రేమ అంటే దానికి ప్రతిష్ఠ.",
        "ప్రేమ అంటే మన జీవితానికి అర్ధం.",
        "ప్రేమ అంటే వాడికి ప్రియతమను సేవించడం.",
        "ప్రేమ అంటే ఒక ఆదర్శం.",
        "ప్రేమ అంటే ఒక ప్రకారం మూడు వార్తలను చేసేది.",
        "ప్రేమ అంటే తన జీవితంలో ఒక సార్థక గురి.",
        "ప్రేమ అంటే సాధారణ వారికి అద్భుతం.",
        "ప్రేమ అంటే ఆత్మగౌరవం.",
        "ప్రేమ అంటే దేవుడి ప్రతిష్ఠ.",
        "ప్రేమ అంటే ఒక ఉదాహరణ.",
        "ప్రేమ అంటే తనంగా ఉండడానికి అనుమతి.",
        "ప్రేమ అంటే దేవుడు, వారికి ఆరాధన.",
        "ప్రేమ అంటే దానికి ప్రతిష్ఠ.",
        "ప్రేమ అంటే మన జీవితానికి అర్ధం.",
        "ప్రేమ అంటే వాడికి ప్రియతమను సేవించడం.",
        "ప్రేమ అంటే ఒక ఆదర్శం.",
        "ప్రేమ అంటే ఒక ప్రకారం మూడు వార్తలను చేసేది.",
        "ప్రేమ అంటే తన జీవితంలో ఒక సార్థక గురి.",
        # Add Love Quotes in Telugu here
    ],
    'devotional-english': [
        "Devotion is the key that unlocks the door to spiritual fulfillment.",
        "In the silence of prayer, we find the presence of God speaking to our hearts.",
        "Faith is not just believing in God but trusting in His perfect timing.",
        "Surrendering to the divine will is the path to true peace and contentment.",
        "The journey of the soul is guided by the light of faith.",
        "Prayer is a conversation with the Divine, a sacred dialogue that transcends words.",
        "God's love is the anchor that steadies our ship in the stormy seas of life.",
        "In every trial, find solace in the comforting embrace of God's grace.",
        "Through devotion, we discover the profound connection between our soul and the Divine.",
        "Each step taken in faith is a step toward spiritual enlightenment.",
        "The heart's devotion is the sweetest melody in the symphony of divine love.",
        "In prayer, we offer our worries to God and receive His peace in return.",
        "Devotion is the fragrance that lingers in the temple of the heart.",
        "The divine presence is felt in the stillness of a soul surrendered to God.",
        "Prayer is not asking; it is a longing of the soul. It is daily admission of one's weakness. - Mahatma Gandhi",
        "Faith is taking the first step even when you don't see the whole staircase. - Martin Luther King Jr",
        "God's mercy is fresh and new every morning. - Joyce Meyer",
        "Let your faith be bigger than your fears, and your actions louder than your words.",
        "The Lord is near to all who call on him, to all who call on him in truth. - Psalm 145:18",
        "God's love is like a river; it never stops flowing, it just keeps going.",
        "The more you trust God, the more He amazes you.",
        "Prayer is not an escape; it is an encounter with God.",
        "God's plan is always the best. Sometimes the process is painful and hard, but don't forget that when God is silent, He's doing something for you.",
        "Fear ends where faith begins.",
        "God often uses our deepest pain as the launching pad for our greatest calling.",
        "When you can't put your prayers into words, God hears your heart.",
        "God has a purpose for your pain, a reason for your struggles, and a reward for your faithfulness. Don't give up!",
        "Faith is not knowing what the future holds, but knowing who holds the future.",
        "Prayer is not asking for what you think you want, but asking to be changed in ways you can't imagine.",
        "In the middle of difficulty lies opportunity. - Albert Einstein",
        "Worry is a conversation you have with yourself about things you cannot change. Prayer is a conversation you have with God about things He can change.",
        "God's love is like a flame that never goes out; it burns eternal in our hearts.",
        "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
        "God is most glorified in us when we are most satisfied in Him. - John Piper",
        "The more you pray, the less you'll panic. The more you worship, the less you worry. You'll feel more patient and less pressured.",
        "Your talent is God's gift to you. What you do with it is your gift back to God.",
        "Be still and know that I am God. - Psalm 46:10",
        "Sometimes God calms the storm, and sometimes He lets the storm rage and calms His child.",
        "Start each day with a grateful heart.",
        "God's love for you is unconditional and everlasting. You are His precious creation.",
        "Prayer is not just asking God for things; it is also taking time to listen to what He has to say.",
        "God's love is like the sun; it never stops shining, even on the darkest days.",
        "Faith is not the absence of fear, but the presence of trust.",
        "The more you trust God, the less you need to understand.",
        # Add Devotional Quotes in English here
    ],
    'devotional-telugu': [
        "దేవుడు మనకు సహాయకుడు, మన రక్షకుడు. - తెలుగు శ్రేష్ఠుల మాట",
        "శ్రీకృష్ణ పరమాత్మ మరియు భగవద్గీత వాక్యాల మూలక మానవత్వాన్ని మెరుగుపరచాడు. - తెలుగు శ్రేష్ఠుల మాట",
        "శ్రీరామ పరమాత్మ, మనమునకు ఆదర్శ చరిత్ర. - తెలుగు శ్రేష్ఠుల మాట",
        "దేవుడు మన పరమ గురువు, మన మార్గదర్శకుడు. - తెలుగు శ్రేష్ఠుల మాట",
        "శివుడు కనపడకుండా సర్వ జగన్నాయకుడు. - తెలుగు శ్రేష్ఠుల మాట",
        "మన జీవితాన్ని శ్రేయస్కరమైన దానం అందజాని శ్రీవారికి నామము రామానామము. - తెలుగు శ్రేష్ఠుల మాట",
        "సర్వశక్తి శ్రీకృష్ణ మన పరమ మేధావి. - తెలుగు శ్రేష్ఠుల మాట",
        "సర్వదేవ సర్వభూతేషు దయాసింధుః. - తెలుగు శ్రేష్ఠుల మాట",
        "ఆదిశక్తి పార్వతి మన రక్షకుడు. - తెలుగు శ్రేష్ఠుల మాట",
        "సర్వాంతర్యామి విష్ణువు మన పరమ పరమేష్ఠి. - తెలుగు శ్రేష్ఠుల మాట",
        "శ్రీరామ మనమునకు ఆదర్శ చరిత్రలో ఉన్నాడు. - తెలుగు శ్రేష్ఠుల మాట",
        "శ్రీరామ దాని భక్తులను రక్షించాడు. - తెలుగు శ్రేష్ఠుల మాట",
        "భగవద్గీత మన జీవితంలో మార్గదర్శకమైన గ్రంథము. - తెలుగు శ్రేష్ఠుల మాట",
        "భగవంతుని కార్యాలు చేయడానికి ప్రేమ తగ్గిన ప్రముఖ మార్గం. - వివేకానంద",
        "దేవుని ప్రేమతో మన హృదయం సంపూర్ణ భగవంతునికి క్రియాశీలమైన వ్యక్తి అవుతుంది. - ఆది శంకరాచార్య",
        "భగవంతుని ఆరాధన అంతర్ముఖ సుఖాన్ని కలిగిస్తుంది. - శ్రీ రామానుజ",
        "దేవునికి ప్రేమ కలిగించేందుకు శరీరమే కారణం. - స్వామి వివేకానంద",
        "దేవుని ప్రేమ వాడి ఆరాధన అనే దిశగా ఉండాలి. - రామానుజాచార్య",
        "దేవుడు దైవత్వమును కలిగించాలి, మరియు అన్యాయాలను కలిగించకూడదు. - ఆది శంకరాచార్య",
        "దేవుని ఆరాధనకు ప్రణాళికగా అభివృద్ధి అవసరం. - రామానుజాచార్య",
        "దేవునికి ప్రేమ అనే ఆధారంపరమైన భక్తి. - శ్రీ చైతన్య మహాప్రభు",
        "దేవుని ప్రేమతో జీవితం సంపూర్ణ అర్పితం అవాలి. - స్వామి వివేకానంద",
        "దేవుని ప్రేమ అంతర్ముఖ సుఖాన్ని కలిగించేందుకు ముఖం స్థానం. - రామానుజాచార్య",
        "దేవుని ప్రేమ దృఢముగా ఉండాలి, మరియు అతనికి పారిపాటముగా ఉండాలి. - వివేకానంద",
        "దేవునికి ప్రేమ అంతర్ముఖ సుఖాన్ని కలిగించేందుకు ప్రతిదినం ఆరాధన చేసేందుకు ముఖం స్థానం. - రామానుజాచార్య",
        "దేవుని ప్రేమ అంతర్ముఖ సుఖాన్ని కలిగించేందుకు భగవంతుడు పరిచయము చేసేందుకు శ్రీమహావిష్ణు రూపముగా అవాలి. - రామానుజాచార్య",
        "దేవుని ప్రేమతో జీవితం సంపూర్ణ అర్పితం అవాలి. - శ్రీ చైతన్య మహాప్రభు",
        "భగవంతుని ఆరాధన ప్రణయాన్ని కలిగించేందుకు దేవుడు అలంకారాన్ని తోడే ఉండాలి. - రామానుజాచార్య",
        "భగవంతుని ఆరాధన వినయాన్ని కలిగించేందుకు శ్రీమహాలక్ష్మి దేవి విగ్రహాన్ని శ్రీనివాసుడి ముందు ఉండాలి. - రామానుజాచార్య",
        "భగవంతుని ఆరాధన వినయాన్ని కలిగించేందుకు శ్రీ రాముని విగ్రహాన్ని ఉండాలి. - శ్రీ రామానుజాచార్య",
        "దేవుని ప్రేమ అంతర్ముఖ సుఖాన్ని కలిగించేందుకు భగవానుడు పరిచయము చేసేందుకు విష్ణు రూపముగా అవాలి. - శ్రీ రామానుజాచార్య",
        "దేవుని ప్రేమతో జీవితం సంపూర్ణ అర్పితం అవాలి. - రామానుజాచార్య",
        "భగవంతుని ఆరాధన ప్రణయాన్ని కలిగించేందుకు శ్రీమహాలక్ష్మి దేవి విగ్రహాన్ని శ్రీనివాసుడి ముందు ఉండాలి. - రామానుజాచార్య",
        "భగవంతుని ఆరాధన వినయాన్ని కలిగించేందుకు శ్రీ రాముని విగ్రహాన్ని ఉండాలి. - శ్రీ రామానుజాచార్య",
        # Add Devotional Quotes in Telugu here
    ],
    'devotional-hindi': [
        "जो अध्यात्म ज्ञान की श्रद्धा से भरपूर होता है, वह सबकुछ को देखने में समर्थ है और सबकुछ को देखता है।",
        "कर्म का फल हमारी आदतें बना देता है। यदि हम अच्छे आदतें बनाएंगे, तो अच्छे फल होंगे।",
        "वही जीवन का सबसे बड़ा साधन है, जो हमें हमारी उच्चता की ओर ले जाता है।",
        "भगवान सदैव साथ हैं और हमें कभी अकेला नहीं छोड़ते।",
        "कर्म का त्याग नहीं, कर्म का सही तरीके से निर्वहन ही जीवन का उद्देश्य है।",
        "अपनी कर्तव्यों को भले ही करो, परन्तु उसके बदले कुछ ना चाहो।",
        "जब हम अपने कर्मों में आसक्ति नहीं रखते, तो उनका फल हमें बिना आसक्ति के ही मिलता है।",
        "समय का सही तरीके से उपयोग करना हमारे उद्देश्यों की प्राप्ति में सहायक होता है।",
        "जीवन का सर्वोत्तम उद्देश्य अपने को बेहतर बनाना चाहिए, ना कि दूसरों को बेहतर बनाना।",
        "सच्चे भक्ति से ही मनुष्य अपने उद्देश्यों की प्राप्ति में सफल हो सकता है।",
        "सफलता का सबसे बड़ा रहस्य यह है कि हमें अपनी क्षमताओं को पहचानना है और उनका सही तरीके से उपयोग करना है।",
        "आत्मविश्वास ही एक व्यक्ति को उसके उद्देश्यों तक पहुँचने में सहायक होता है।",
        "भगवान के प्रति पूर्ण श्रद्धा और भक्ति के साथ कर्म करना ही जीवन का असली मतलब है।",
        "जीवन में कोई समस्या हो या फिर सुख, सभी कुछ हमारी सोच पर निर्भर करता है।",
        "किसी भी स्थिति में हमें शांति बनी रखना चाहिए, क्योंकि शांति ही जीवन की सबसे बड़ी धन है।",
        "जीवन में सफलता प्राप्त करने के लिए हमें सकारात्मक रूप से सोचना चाहिए।",
        "हमें अपने कर्मों का परिणाम स्वीकार करना चाहिए और सीखना चाहिए कि हम उन्हें बेहतर तरीके से कैसे कर सकते हैं।",
        "सही कर्म करना हमें सफल बनाता है, और सफलता हमें खुशी और आत्म-संराज्य देती है।",
        "जीवन में सफलता प्राप्त करने के लिए आत्म-नियंत्रण बहुत आवश्यक है।",
        "अपने कर्मों को समर्थन से करना और फल की चिंता नहीं करना ही सही राह है।",
        "अपने कर्मों को भगवान के लिए करना हमें मोक्ष की प्राप्ति में सहायक होता है।",
        "सच्चे धर्म में स्थिरता और समर्पण होता है, जो हमें अच्छे कर्मों की दिशा में बढ़ने में मदद करता है।",
        "जीवन का अर्थ यह नहीं है कि हम कितना काम करते हैं, बल्कि यह है कि हम कैसा काम करते हैं।"
    ],
    'ramayan-hindi': [
        "अपने प्राणी को दुख नहीं पहुँचाना चाहिए।",
        "सीखने के लिए धैर्य रखना हमें सफलता की ऊचाइयों तक पहुँचाता है।",
        "समर्थ और निर्भीक रहना हमें हर कठिनाई को पार करने में सहायक होता है।",
        "अच्छे संस्कारों का पालन करना हमें अच्छे इंसान बनाता है।",
        "अध्ययन और समझदारी से आत्म-निर्माण होता है।",
        "अपनी मित्रता में सत्य और विश्वास को बनाए रखना चाहिए।",
        "समस्त वर्गों के लोगों के प्रति समर्पित रहना हमें समृद्धि दिलाता है।",
        "अपने आप को सबसे कमजोर व्यक्ति मानना और दूसरों को सबसे महत्वपूर्ण मानना हमें अच्छे इंसान बनाता है।",
        "विशेषज्ञता अर्जित करने के लिए प्रतिबद्ध रहना हमें सफलता दिलाता है।",
        "अपने लक्ष्यों को प्राप्त करने के लिए कड़ी मेहनत करना चाहिए।",
        "उदार और दयालु बने रहना हमें सबका साथ दिलाता है।",
        "परिश्रम से ही सफलता मिलती है, इसलिए हमें कभी भी हार नहीं माननी चाहिए।",
        "अच्छे स्वास्थ्य का पालन करना हमें ऊर्जा और उत्साह देता है।",
        "धन की प्राप्ति के लिए ईमानदारी से काम करना चाहिए।",
        "जब तक जीवन में कोई नीति नहीं होती, तब तक उसका महत्व ही नहीं होता।",
        "शिक्षा हमें सच्चे ज्ञान की ओर बढ़ने में सहायक होती है।",
        "अपने आत्मविकास के लिए समय-समय पर विचारशील रहना चाहिए।",
        "सफलता की कीमत में कभी भी संघर्ष करना चाहिए।",
        "जीवन में सफलता प्राप्त करने के लिए अच्छे संबंध बनाए रखना चाहिए।",
        "आत्म-निर्भरता ही एक व्यक्ति को सफल बनाती है।",
        "जीवन के हर क्षण को खुशी से जीना चाहिए।",
        "सच्चा सफलता यह है कि हम अपने लक्ष्यों की प्राप्ति में सहायक हों।",
        "जीवन में सफलता प्राप्त करने के लिए सकारात्मक सोचना चाहिए।",
        "आत्मा को शांति और आत्म-निर्माण में सहायक होने के लिए ध्यान में रहना चाहिए।"
    ],
}
